### ISSUE TITLE
"MP4 encoder is not available on this platform" on MacOS

### ISSUE THREAD

**Issue by johnnyshi1225** [unity3d-jp/FrameCapturer#16]
This appeared when I'm using FrameCapturer on MacOS, Unity 2017.0f1. But I can see that there are some plugins, and I guess that fccore.bundle is for MacOS?

**Comment by i-saint** [comment]
MP4 recording is available only on Windows for now.

**Comment by johnnyshi1225** [comment]
Thanks for replying! We are making videos with Unity on MacOS. Is there any good way of output video(.mp4)?

**Comment by i-saint** [comment]
any other recorders should work. you can record as exr sequence (best for non-realtime project) or webm video and covert it to mp4 by other tools (e.g. ffmpeg),

**Comment by johnnyshi1225** [comment]
Is there any document of FrameCapturer which can explain each and every params in details? Especially those in encoder settings.

**Comment by johnnyshi1225** [comment]
BTW, is there any good document for making video by Unity? Including FrameCapturer usage and ffmpeg to output high quality video. I think "Adam" is awesome but I just cannot output this kind of extremely great quality.

**Comment by i-saint** [comment]
there is no proper document for now, but FrameCapturer exposes only basic and generic encoder parameters. I think ffmpeg's document can explain most of it.
Adam is recorded by internal tools and  encoded with ffmpeg.

**Comment by johnnyshi1225** [comment]
I see. Is there any great group in which there are people who want to create video with Unity that I can join?

**Comment by i-saint** [comment]
I have no idea.
