### ISSUE TITLE
Possible NVENC support?

### ISSUE THREAD

**Issue by ikriz** [unity3d-jp/FrameCapturer#17]
Nvidia NVENC encoding would relieve the CPU of encoding time making it faster :+1:

**Comment by ikriz** [comment]
Nevermind  I said nothing, your awesome :)

**Comment by i-saint** [comment]
there is code to use NVENC as you noticed, and it at least works, but it is disabled for various reason. we reached the conclusion that using OS-provided encoder is the only practical solution for us.
(you may also noticed there is code to use AMD VCE and Intel QSV, but it is unfinished and doesn't work)

**Comment by ikriz** [comment]
Support for at least having the option of hardware encoding methods would be great, as rendering the camera can be very cpu/gpu intensive. Already implemented NVENC myself once, would be great if unity supported this.
