### ISSUE TITLE
MP4 output only writes a file of 32 bytes [Windows 7]

### ISSUE THREAD

**Issue by ikriz** [unity3d-jp/FrameCapturer#18]
All the output I get using the MovieRecorder Component (the 32byte file).
[20170711_121050.zip](https://github.com/unity3d-jp/FrameCapturer/files/1138500/20170711_121050.zip)

Tried using the dev branch but the dll's are missing from the unity project.
[update]The dll's are being ignored in the github repo by the looks of it[/update]

**Comment by i-saint** [comment]
I got another bug report for this issue, but I could have not reproduce it. I need more information. 
can you send me [Editor.log](https://docs.unity3d.com/Manual/LogFiles.html)?  does this issue occur only on mp4 recorder? (what about another recorder?) does it always happen or under some condition?

**Comment by ikriz** [comment]
The webm encoder does indeed work, it's just the mp4 encoder for me that doesnt.
I'm running it on a windows machine (with nvidia card). The only output in the editor log is the begin and end recording messages.

**Comment by i-saint** [comment]
I think I figured it out.  this plugin is using a feature that may not be supported on Windows 7. if you can build and test plugin, replace "eAVEncH264VProfile_High" with "eAVEncH264VProfile_Main" in [this line](https://github.com/unity3d-jp/FrameCapturer/blob/20170531/Plugin/fccore/Encoder/MP4/fcMP4_Windows.cpp#L223).

building this plugin is simple.  just open Plugin/fccore.sln with VisualStudio 2015 or 2017 and build it.

**Comment by i-saint** [comment]
I realized we don't have Windows 7 test environment anymore. can you test this build?
[fccore.zip](https://github.com/unity3d-jp/FrameCapturer/files/1143878/fccore.zip)

**Comment by ikriz** [comment]
I tested your dll with the test scene. Still no video frames, the audio does get written out, kinda wanna get the DebugImpl working but not sure how. Have successfully build the plugin though.

**Comment by i-saint** [comment]
hmm, there must be another features not supported on Windows 7. H264 encoder on Windows 7 seems quite limited. ( https://msdn.microsoft.com/en-us/library/windows/desktop/dd797816?f=255&MSPPError=-2147217396 )
I think I will label it "MP4 recorder is available on Windows 8 or later" instead of fix it.

**Comment by i-saint** [comment]
I noticed Windows 7's share is still [far from ignorable](http://store.steampowered.com/hwsurvey/). I need to dig into bit more..

can you test this build? [fccore.zip](https://github.com/unity3d-jp/FrameCapturer/files/1145340/fccore.zip)

**Comment by ikriz** [comment]
Sorry for the late reply, tested the last build but the same thing still happens. The whole company here still uses win 7, unity hardware stats say the same thing a good percentage of users still are on win7.

**Comment by i-saint** [comment]
thanks for the info.
I need my own Windows7 machine to investigate furthermore. please wait for a while.

**Comment by filibis** [comment]
Hi, i just wanted to confirm that i'm having same issue on win 7 as well. Looking forward to your solution.

OS: Windows 7 Pro 64-bit (6.1, Build 7601)
Unity 2017.1.0f3

**Comment by i-saint** [comment]
FYI: it can take a month or more, or maybe I give up. if you are in a hurry, you'd better look for another solution.

**Comment by filibis** [comment]
Thanks for heads up. No worries, i'm already using [this FFmpegOut](https://github.com/keijiro/FFmpegOut). I was just exploring better alternatives since it has [this high-res issue](https://github.com/keijiro/FFmpegOut/issues/11).

Long live Unity Japan! :smile:

**Comment by ikriz** [comment]
I found an error "Transform_ProcessOutputError" in the MFT trace logs (based on https://blogs.msdn.microsoft.com/mf/2010/05/20/using-event-viewer-to-trace-media-foundation/):
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-MediaFoundation-MFReadWrite" Guid="{4b7eac67-fc53-448c-a49d-7cc6db524da7}" /> 
  <EventID>203</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>3</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x2000000000000000</Keywords> 
  <TimeCreated SystemTime="2017-07-26T19:34:13.424184200Z" /> 
  <EventRecordID>4</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="29264" ThreadID="10280" ProcessorID="0" KernelTime="0" UserTime="0" /> 
  <Channel>Microsoft-Windows-MediaFoundation-MFReadWrite/Transform</Channel> 
  <Computer>#REMOVED#</Computer> 
  <Security UserID="S-1-5-21-1343024091-1957994488-1060284298-34298" /> 
  </System>
- <EventData>
  <Data Name="Object">0x3d27a7d0</Data> 
  <Data Name="StreamIndex">1</Data> 
  <Data Name="Transform">0x10fb1d8</Data> 
  <Data Name="ErrorCode">3222105458</Data> 
  </EventData>
  </Event>

Hoping this is not worthless information...?

**Comment by i-saint** [comment]
I couldn't find any useful information about Transform_ProcessOutputError... but I really appreciate your help.

**Comment by whitespeed** [comment]
same problem with @filibis , only audio has been recorded. And My PC is also Windows 7 with Unity 2017.1.0f3

**Comment by ikriz** [comment]
Easiest workaround is to upgrade your system to windows 10 (this solved the issue for me)
