### ISSUE TITLE
Massive FPS drop

### ISSUE THREAD

**Issue by Sonky108** [unity3d-jp/FrameCapturer#19]
Hi,

I have tested the unitypackage and it used to work great. Unfortunately now when I am trying to record video I receive massive FPS drop. While recording .mp4 video from Frame Buffer with audio FPS in my Unity application are around value of "Capture Every Nth Frame". If I left it by default set to 1 application works on 1FPS. 

Unity Profiler says that in this case it takes around 1000 ms on PlayerEndOfFrame->MovieRecorder.OnPostRender(). Is it possible somehow to maintain at least 30 FPS? 

Working on Windows 10, unitypackage downloaded from description.

Thanks in advance.

**Comment by Sonky108** [comment]
Deep profiling says that almost all of the second is taken by MP4Encoder.AddVideoFrame(). It's strange that it records normally around first 30 frames and then massive drop begins.

**Comment by i-saint** [comment]
I can't reproduce the issue. I need more information. can you send me [Editor.log](https://docs.unity3d.com/Manual/LogFiles.html)?

**Comment by Sonky108** [comment]
Hey,

sorry for late replay I was out of computer during weekend. Here is Editor.Log

https://pastebin.com/rWCe6c5g

**Comment by i-saint** [comment]
thanks, but please keep in mind, fixing issue that I can't reproduce is very difficult. I need your help to fix it.
what about other questions?
can you send me your project? (I think this issue is dependent on your computer, not the project, but I desperately need more information)

you can attach files to here (drag file to form)

**Comment by Sonky108** [comment]
Thanks for reply. I have tried to reproduce the issue by making blank project and import new package and it seems to work nicely. I have also recreate Camera component and lag disappeared. I will test it and let You know tomorrow or in two days.

**Comment by i-saint** [comment]
if you managed to reproduce, please check whether it happens on WebM recorder as well. it is important.

**Comment by LeSphax** [comment]
Hello, thank you for making this nice tool available to everyone !

I have the same problem as Sonky.
After recording around 150 frames the OnPostRender function starts taking 1 second for every frame.

I tried disabling windows defender but it didn't help.
But it doesn't happen when recording with the webM format.

I actually managed to reproduce it on the example scene "Test":

* Remove the GBuffer and Audio Recorder scripts
* Change video format to mp4
* Uncheck Fix delta time
* Set End Frame to 500

After few seconds OnPostRender should start taking 1 second for about 20 frames and then go back to normal.

I will be glad to provide more info if you need it :)
