### ISSUE TITLE
Feature Request: HEVC / h265 support

### ISSUE THREAD

**Issue by soraryu** [unity3d-jp/FrameCapturer#21]
Since you are using the nvEncodeAPI for encoding, a good thing to have would be HEVC encoding. This is much faster and allows for higher output resolutions (up to 8k at near realtime speeds).

**Comment by i-saint** [comment]
we are using OS-provided encoder because it is an only practical solution for us. there is no plan to work on hardware encoder for now. ( https://github.com/unity3d-jp/FrameCapturer/issues/17 )
