### ISSUE TITLE
DllNotFoundException: fccore

### ISSUE THREAD

**Issue by artyom-zuev** [unity3d-jp/FrameCapturer#22]
I'm sorry if I'm missing something obvious, but it looks like the current version of the project is not including the fccore.dll. Running the sample scene results in nothing but "DllNotFoundException: fccore" messages.

**Comment by i-saint** [comment]
read the document.

**Comment by artyom-zuev** [comment]
Can you point me to the documentation, please? I can't find any links to it in the GitHub repository description nor see any documentation files within the repository itself.

**Comment by filibis** [comment]
I believe he meant this [issue #20](https://github.com/unity3d-jp/FrameCapturer/issues/20) which same question has been asked an replied.

**Comment by i-saint** [comment]
@artyom-zuev https://github.com/unity3d-jp/FrameCapturer

**Comment by i-saint** [comment]
for those who can't read README.md for unknown reason:

#### Usage
1. Import this package to your project: [FrameCapturer.unitypackage](https://github.com/unity3d-jp/FrameCapturer/releases/download/20170715/FrameCapturer.unitypackage) (note: this link maybe obsolete. you can get latest version from [Releases](https://github.com/unity3d-jp/FrameCapturer/releases))
2. Add recorder component to camera (Add Component -> UTJ -> FrameCapturer -> * Recorder)
Setup recorder settings and capture
