### ISSUE TITLE
Is there any to build for android and ios ?

### ISSUE THREAD

**Issue by wangjianpeng** [unity3d-jp/FrameCapturer#23]
I want to use this plugin for android and ios real time recorder; but i find this plugin is just for win and mac without rebuild source.
Can i build  source for android and ios to record ?

**Comment by thomasmoon** [comment]
This would be great.  Also looking forward to mp4 support on OSX. 🙏

**Comment by i-saint** [comment]
we won't do it. but pull request is welcome.
