### ISSUE TITLE
Performance on output 4K video(Only about 10FPS)

### ISSUE THREAD

**Issue by frideal** [unity3d-jp/FrameCapturer#24]
Dose GenericFrameRecorder Use Multi thread when Output 4K Mp4 file?

When I upgrade My computer device config:

Window10 64 bit
Intel Core i9-7900 @ 3.30GHZ
525GB ssd
Gtx 1080 ti 11GB

The Recorder process always output about 10fps (My scene just contains just One character)

When Look up Profiler window
I find that Texture2D.ReadPixels(); always about 50ms when I want to get 4K video.Or can we move this Texture2D.ReadPixels() into MultiThread?

Is there any way to promote the process of output 4K videos?

Thanks Very much.

**Comment by frideal** [comment]
public static void fcLock(RenderTexture src, TextureFormat dstfmt, Action<byte[], fcPixelFormat> body)
{
var tex = new Texture2D(src.width, src.height, dstfmt, false);
RenderTexture.active = src;
tex.ReadPixels(new Rect(0, 0, tex.width, tex.height), 0, 0, false);
tex.Apply();
body(tex.GetRawTextureData(), fcGetPixelFormat(tex.format));
UnityEngine.Object.Destroy(tex);
}

In the Profiler I found that the bottleneck of GenericFrameRecorder is ReadPixels (about 50ms - 60ms).

**Comment by i-saint** [comment]
4K video recording is inevitably slow.
