### ISSUE TITLE
No preview and no record

### ISSUE THREAD

**Issue by AkSponkynot** [unity3d-jp/FrameCapturer#3]
Hi,

I have some issues, when I integrated a GifRecorder with MovieRecorderEditorUI.prefab or MovieRecorderUI.prefab, I had no preview in UI and it's impossible to save the record.
I taked the time to import FrameCapturer.Unitypackage and FAACSelfBuild.Unitypackage

Do you think it's because I'm on MacOS? If yes, there is a workaround?

**Comment by i-saint** [comment]
yes, currently works only on Windows. we are planning to provide Mac version, but not sure when it will be released. maybe you can build plugin from source by yourself.
