### ISSUE TITLE
Steps for linux build?

### ISSUE THREAD

**Issue by spartako** [unity3d-jp/FrameCapturer#34]
What steps do I need to follow to make this work on linux? 
Are there any dependencies?
thnx

**Comment by spartako** [comment]
Using cmake reveals some dependencies. Most of them are easily available, except libyuv and libwebm. 
How do you get a hold of these two?

libwebm isn't easy to build from source, at least on a Linux machine. Could you guys provide with some more detail on how to get it?

**Comment by spartako** [comment]
right, thanks

**Comment by NinjaaSamurai** [comment]
Hi  @i-saint, @spartako,
            I am trying to make linux build. If you are successful in doing it already, can you please share the steps to build it as Standalone Linux app. Or if you can share the .so file for linux build it would be helpful.

Thanks

**Comment by spartako** [comment]
@NinjaaSamurai Haven't succeded yet. Same here if you are able to get the package for linux, do tell.

**Comment by hk1ll3r** [comment]
Any luck since last year?

**Comment by ashokcse07** [comment]
No, I was not able to do it. I used windows build.
