### ISSUE TITLE
Add Linux binary

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/FrameCapturer#35]

**Comment by spartako** [comment]
Great news!

**Comment by ashokcse07** [comment]
Waiting for it!!!!!!!. Please release as soon as possible!!!!!

**Comment by ashokcse07** [comment]
Hi,
    Thanks for closing the issue and completing it. I can see 100% complete
next release. I am eagerly waiting for the next release to happen. I had
myself tried build it for linux and got libfccore.so but there are few more
dependencies where I am stuck. So I am waiting for your next release.


Thanks

**Comment by se7enXF** [comment]
I meet the same problem. Where is the next release? I build the fccore in linux and stuck in libwebm.
