### ISSUE TITLE
Multiple cameras issue

### ISSUE THREAD

**Issue by Apasal14** [unity3d-jp/FrameCapturer#38]
Hi,
I have a somewhat weird question, and I'm not an expert in scripting at all. Here's my issue: I have an empty gameobject in my scene with 5 cameras as children of this empty gameobject. Each child has the G Buffer Recorder script attached to it as a component with the exact same settings. When i press play I will only get 1 .exr file render instead of 5. Is it because the cameras overwrite eachothers render? And if so, which script should I look at for defining the filename of the render, so that I can configure it to use the current camera name that the script is attached to as the filename? Or is there another problem? Help is very much appreciated.

**Comment by i-saint** [comment]
just change "Output Dir".

**Comment by Apasal14** [comment]
So there is no way to have the renders saved to the same directory? It could be really awesome to have all the renders from the different camera views in one folder, instead of many.

**Comment by Apasal14** [comment]
I found a way to deal with it so all the frames are saved to the same directory.
