### ISSUE TITLE
Vertical mirrored renders

### ISSUE THREAD

**Issue by Apasal14** [unity3d-jp/FrameCapturer#39]
Extension on issue #38 where I found a way to save the renders to the same directory. Camera 2 gives me a proper render. For some reason, Camera 1, Camera 3, Camera 4, Camera 5 gives me vertically mirrored renders. Any ideas? I've attached the renders below.

![camera1_framebuffer_0000](https://user-images.githubusercontent.com/15028105/48475845-00724b80-e7fe-11e8-9812-9eec914fea5e.png)
![camera2_framebuffer_0000](https://user-images.githubusercontent.com/15028105/48475852-023c0f00-e7fe-11e8-9f5d-e8679a1a66b1.png)
![camera3_framebuffer_0000](https://user-images.githubusercontent.com/15028105/48475857-049e6900-e7fe-11e8-99f8-5579e6b5d31f.png)
![camera4_framebuffer_0000](https://user-images.githubusercontent.com/15028105/48475861-0831f000-e7fe-11e8-8e26-e1824b574859.png)
![camera5_framebuffer_0000](https://user-images.githubusercontent.com/15028105/48475873-0cf6a400-e7fe-11e8-9f5b-1b1cf8764084.png)

**Comment by Apasal14** [comment]
i fixed it so im going to close this issue down now

**Comment by i-saint** [comment]
I want to know what changes you made. can you fork the repo and commit changes to it?
