### ISSUE TITLE
mp4 video bitrate setting has no effect

### ISSUE THREAD

**Issue by XeonG** [unity3d-jp/FrameCapturer#4]
video bitrate for mp4 encoder has no effect at all on the encoded video's bitrate

tested using the h264 win7 x64

maybe expose more of the h264 encoder settings on the MP4Recorder

**Comment by kefniark** [comment]
win10 x64 with unity 5.5, same issue +1

**Comment by XeonG** [comment]
isaint seems to have a new dev branch with webm support .. I tried to get it working, didn't get far.. maybe you can try and see if its improved things.

**Comment by azu1129** [comment]
same here. Windowns7 unity5.4.2

videos are created 300-800kbps.

**Comment by azu1129** [comment]
I changed below code and got good quality mp4 file :) 

` param.iRCMode = RC_BITRATE_MODE;`
to
`param.iRCMode = RC_QUALITY_MODE;`
at Plugin/Encoder/fcOpenH264Encoder.cpp LINE:94

but yet bitrate value doesnt work.

**Comment by azu1129** [comment]
I think that SEncParamExt inteface is needed to work bitrate value.

setting is like this.
```
param.iRCMode              = RC_OFF_MODE;
param.iNumRefFrame         = 1;
param.bEnableAdaptiveQuant = false;
param.bEnableFrameSkip                     = true;    // true: need for set bitrate
```

but SEncParamExt has many parameters and confusing. If anyone knows, please tell me how to set SEncParamExt as  SEncParamBase default.

**Comment by i-saint** [comment]
fixed in recent versions.
