### ISSUE TITLE
FC Installed but can't capture anything . .

### ISSUE THREAD

**Issue by philiprhoades** [unity3d-jp/FrameCapturer#40]
I am trying to capture a talking head in the game window but using the default video capture settings and hitting play, plays the talking head but nothing is saved in the capture dir - what am I missing?

Thanks,
Phil.

**Comment by i-saint** [comment]
read the document and follow the instructions.

**Comment by philiprhoades** [comment]
Very helpful response . . why did you even bother to type anything?

**Comment by i-saint** [comment]
your question is too vague and that was all I can say.
if you are sure you followed the instructions and still need help, give me more detailed information. at least Editor.log. (https://docs.unity3d.com/Manual/LogFiles.html)
