### ISSUE TITLE
FrameCapturer does not work in unity 2019

### ISSUE THREAD

**Issue by xintang083** [unity3d-jp/FrameCapturer#47]
Hi, I am trying to record but it does not work yet, it told me some message that 

DllNotFoundException: fccore
UTJ.FrameCapturer.ExrEncoder.Initialize (System.Object config, System.String outPath) (at Assets/UTJ/FrameCapturer/Scripts/Encoder/ExrEncoder.cs:22)
UTJ.FrameCapturer.MovieEncoder.Create (UTJ.FrameCapturer.MovieEncoderConfigs c, System.String path) (at Assets/UTJ/FrameCapturer/Scripts/Encoder/MovieEncoder.cs:158)
UTJ.FrameCapturer.MovieRecorder.BeginRecording () (at Assets/UTJ/FrameCapturer/Scripts/MovieRecorder.cs:127)
UTJ.FrameCapturer.RecorderBase.Update () (at Assets/UTJ/FrameCapturer/Scripts/RecorderBase.cs:265)
![image](https://user-images.githubusercontent.com/51780925/59419841-5b087000-8dfe-11e9-888c-8dea94109aa6.png)

and my version is unity 2019 .2  
many thanks

**Comment by ArturKovacs** [comment]
I'm suspecting you downloaded the source from github instead of the unitypackage from the [releases page](https://github.com/unity3d-jp/FrameCapturer/releases). The unitypackage should contain those DLLs.

**Comment by arodic** [comment]
The latest release was from 2017. Any chance a new release will be published for 2019?
