### ISSUE TITLE
Any option to have it capture gui interface?

### ISSUE THREAD

**Issue by XeonG** [unity3d-jp/FrameCapturer#5]
I thought "CameraEvent.AfterEverything" might have included the interface stuff, being that its called 'AfterEverything'.. it seems not.

**Comment by AronDavis** [comment]
I would like this as well.

**Comment by jasonm-unity** [comment]
absolutely, but not in the first role out.
V1 is very much geared towards exporting the image rendering output, while the UI is actully a second stage pass to add to the rendered image.

**Comment by i-saint** [comment]
it seems there is no way other than using RenderTexture (render scene and UI to RenderTexture, record it with another camera).
