### ISSUE TITLE
MP4: No audio track is created

### ISSUE THREAD

**Issue by ClintChil** [unity3d-jp/FrameCapturer#6]
I haven't been able to record audio to MP4 videos created with FrameCapturer. 
The `fcAPI.fcMP4AddAudioFrame(m_ctx, samples, samples.Length);` method is called but an audio track is never created on the MP4 file. Is this a known issue?

**Comment by kaSakumaKatsuya** [comment]
Me,too

**Comment by Knive** [comment]
Same issue, too bad because the plugin itself has good performance

**Comment by i-saint** [comment]
fixed in recent versions. (switched encoder to WMF from OpenH264 & FAAC)
