### ISSUE TITLE
Poor performance with Gif

### ISSUE THREAD

**Issue by kefniark** [unity3d-jp/FrameCapturer#9]
Thanks, I like the idea of this project.
This can be really convenient for some debugging tools and to advertise new features.

I did some test with a small project (unity2d)
![image](https://cloud.githubusercontent.com/assets/4903529/20593360/6c058f30-b275-11e6-9933-dd035cc24c2f.png)

But the performance of Gif recording is poor, I tried to set the resolution to 480p and the framerate is horrible and there are lot of Jittering.
The same king of setting with Mp4 Recorder is smooth at 60 fps

**Comment by i-saint** [comment]
maybe it's counterintuitive, but gif recording is far far slower than mp4 and it is unlikely to be improved.
